spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DB:postit_db}?autoReconnect=true&useSSL=false&connectTimeout=30000
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: ${GOOGLE_REDIRECT_URI}
            scope:
              - email
              - profile

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

      lettuce:
        pool:
          max-idle: 8
          min-idle: 0
          max-active: 8


jwt:
  secret-key: ${JWT_SECRET_KEY}

main-page: https://post-it-service.shop