events {}

http {
	access_log /var/log/nginx/access.log;
	error_log /var/log/nginx/error.log warn;

	# HTTP를 HTTPS로 리다이렉트
	server {
		listen 80;
		server_name _;
		return 301 https://$host$request_uri;
	}

	# HTTPS 서버
	server {
		listen 443 ssl http2;
		server_name _;

		ssl_certificate /etc/letsencrypt/live/post-it-00-service.duckdns.org/fullchain.pem;
		ssl_certificate_key /etc/letsencrypt/live/post-it-00-service.duckdns.org/privkey.pem;
		
		ssl_protocols TLSv1.2 TLSv1.3;
		ssl_ciphers HIGH:!aNULL:!MD5;
		ssl_prefer_server_ciphers on;

		# API 요청 처리
		location /api {
			proxy_pass http://springboot-web:8080;
			proxy_set_header Host $host;
			proxy_set_header X-Real-IP $remote_addr;
			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
			proxy_set_header X-Forwarded-Proto $scheme;
		}

		# 정적 웹 리버스 프록시 (Flutter)
		location / {
			proxy_pass http://flutter-web:80;
			proxy_set_header Host $host;
			proxy_set_header X-Real-IP $remote_addr;
			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
			proxy_set_header X-Forwarded-Proto $scheme;
			
			proxy_hide_header ETag;
			add_header Cache-Control "no-store";
		}
	}
}
