name: CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"

    - name: Debugging Docker variables
      run: |
        echo "DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}"
        echo "DOCKER_REGISTRY_URL: ${{ secrets.DOCKER_REGISTRY_URL }}"
        
    - name: Build and push backend Docker image
      run: |
        docker buildx build --platform linux/amd64,linux/arm64 -t ${{ secrets.DOCKER_REGISTRY_URL }}/springboot-web:latest ./postIt-backend --push

    - name: Build and push frontend Docker image
      # env:
      #   DOCKER_REGISTRY_URL: ${{ secrets.DOCKER_REGISTRY_URL }}
      run: |
        docker buildx build --platform linux/amd64,linux/arm64 -t ${{ secrets.DOCKER_REGISTRY_URL }}/flutter-web:latest ./postIt-frontend --push

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        script: |
          # Pull the latest images
          docker pull ${DOCKER_REGISTRY_URL}/springboot-web:latest
          docker pull ${DOCKER_REGISTRY_URL}/flutter-web:latest

          # Restart the containers using docker-compose
          cd /home/ec2-user
          docker compose -f docker-compose.prod.yml down
          docker compose -f docker-compose.prod.yml up --build
